from .create_property_listing import CreatePropertyListingController
from .mark_sold_property_listing import MarkropertyListingController
from .remove_property_listing import RemovePropertyListingController
from .update_property_listing import UpdatePropertyListingController
from .view_property_listing import ViewPropertyListingController
from .view_buyer_property_listing import ViewBuyerPropertyListingController
from .search_sold_property_listing import SearchSoldPropertyListingController
from .search_managed_property_listing import SearchManagedPropertyListingController
from .search_new_property_listing import SearchNewPropertyListingController
from .search_owned_property_listing  import SearchOwnedPropertyListingController
from .view_stats_sold import ViewStatsVizOfSoldPlController
from .calculate_mortgage import CalculateMortgageController

create_property_listing_controller = CreatePropertyListingController(name="create_property_listing", import_name=__name__)
mark_sold_property_listing_controller = MarkropertyListingController(name="mark_sold_property_listing", import_name=__name__)
remove_property_listing_controller = RemovePropertyListingController(name="remove_property_listing", import_name=__name__)
update_property_listing_controller = UpdatePropertyListingController(name="update_property_listing", import_name=__name__)
view_property_listing_controller = ViewPropertyListingController(name="view_property_listing", import_name=__name__)
view_buyer_property_listing_controller = ViewBuyerPropertyListingController(name="view_buyer_property_listing", import_name=__name__)

view_stats_controller = ViewStatsVizOfSoldPlController(name="view_stats_sold_pl", import_name=__name__)
search_managed_pl_controller = SearchManagedPropertyListingController(name="search_managed_pl", import_name=__name__)
search_new_pl_controller = SearchNewPropertyListingController(name="search_new_pl", import_name=__name__)
search_sold_pl_controller = SearchSoldPropertyListingController(name="search_sold_pl", import_name=__name__)
search_owned_pl_controller = SearchOwnedPropertyListingController(name="search_owned_pl", import_name=__name__)

calculate_mortgage_controller = CalculateMortgageController(name="calculate_mortgage", import_name=__name__)


__all__ = [
	"create_property_listing_controller", "mark_sold_property_listing_controller","view_buyer_property_listing_controller", "view_stats_controller",
	"remove_property_listing_controller", "update_property_listing_controller", "view_property_listing_controller",
	"search_sold_pl_controller", "search_managed_pl_controller", "search_new_pl_controller", "search_owned_pl_controller",
	"calculate_mortgage_controller"
]